# All Sequencial Gurobi Runs 
./bin/flock -i  ./data/TransportModel_1000_750_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_750_500_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_100_100_3_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_1000_5000_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_100_100_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_100_250_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_500_500_3_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_500_500_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_1000_1000_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_1000_500_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_100_100_2_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_750_750_2_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_1000_5000_3_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_1000_2500_2_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_500_750_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_750_750_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_250_100_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_250_250_2_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_1000_1000_2_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_500_500_2_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_250_250_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_500_100_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_250_1000_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_750_750_3_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_750_1000_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_1000_2500_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_250_250_3_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_1000_1000_3_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_1000_2500_3_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_500_1000_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_100_500_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_1000_5000_2_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_500_250_1_equalityConstr.dat  -a cpu_lp_solve
./bin/flock -i  ./data/TransportModel_250_500_1_equalityConstr.dat  -a cpu_lp_solve

# All Parallel Runs
./bin/flock -i  ./data/TransportModel_1000_750_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_750_500_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_100_100_3_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_1000_5000_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_100_100_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_100_250_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_500_500_3_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_500_500_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_1000_1000_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_1000_500_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_100_100_2_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_750_750_2_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_1000_5000_3_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_1000_2500_2_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_500_750_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_750_750_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_250_100_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_250_250_2_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_1000_1000_2_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_500_500_2_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_250_250_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_500_100_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_250_1000_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_750_750_3_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_750_1000_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_1000_2500_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_250_250_3_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_1000_1000_3_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_1000_2500_3_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_500_1000_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_100_500_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_1000_5000_2_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_500_250_1_equalityConstr.dat  -a parallel_uv
./bin/flock -i  ./data/TransportModel_250_500_1_equalityConstr.dat  -a parallel_uv


